#pragma checksum "C:\Users\shant\OneDrive\Dokumenter\GitHub\UnikProjekt\UNIKProjekt\UNIKProjekt\Views\Home\News\Article.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "a94a8fe5ccb19ba61c4c0873d391e987982fbbd3"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Home_News_Article), @"mvc.1.0.view", @"/Views/Home/News/Article.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "C:\Users\shant\OneDrive\Dokumenter\GitHub\UnikProjekt\UNIKProjekt\UNIKProjekt\Views\_ViewImports.cshtml"
using UNIKProjekt;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Users\shant\OneDrive\Dokumenter\GitHub\UnikProjekt\UNIKProjekt\UNIKProjekt\Views\_ViewImports.cshtml"
using UNIKProjekt.Models;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"a94a8fe5ccb19ba61c4c0873d391e987982fbbd3", @"/Views/Home/News/Article.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"568442933e85435526d936f914d6da00b638c84e", @"/Views/_ViewImports.cshtml")]
    public class Views_Home_News_Article : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("test");
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
